AWSTemplateFormatVersion: "2010-09-09"
Description: "Create EC2 Launch Template for EC2 with IMDSv2 Enabled."

Resources:  
  IMDSv2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
        LaunchTemplateName: IMDSv2
        LaunchTemplateData:
          MetadataOptions:
            HttpEndpoint: enabled
            HttpPutResponseHopLimit: 1
            HttpTokens: required