                    - name: Sync_S3_Config_Files
                      action: ExecuteBash
                      inputs:
                        commands:
                          - |
                            #!/bin/bash

                            for path in $(aws s3 ls --recursive {{s3_download_bucket}}/Config/Files/|awk '{print $4}')
                            do
                              tpath=${path#*Config/Files}
                              dpath=${tpath%/*}
                              aws s3 sync s3://{{s3_download_bucket}}/Config/Files$dpath/ $dpath/
                            done

                            aws s3 cp s3://{{s3_download_bucket}}/Config/Ownerships/ownerships /tmp/
                            grep -v "^#" /tmp/ownerships | while read -r line
                            do
                              file=$(echo $line|awk -F ':' '{print $1}')
                              perms=$(echo $line|awk -F ':' '{print $2}')
                              user=$(echo $line|awk -F ':' '{print $3}')
                              group=$(echo $line|awk -F ':' '{print $4}')

                              if [[ -n "$perms" ]];then
                                chmod $perms $file
                              fi

                              if [[ -n "$user" ]];then
                                chown -R $user:$group $file
                              fi

                              ls -l $file

                            done