AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to configure Extra_Configs RolePolicy EC2 SSM Role.
Parameters :
  ManagementAccountNumber:
    Type : 'String'
    Description: 'Account number for the central management account.'
    Default: "169523143400"
  S3DownloadBucket:
    Type : 'String'
    Description: 'S3 Bucket to download Binaries and Scripts From'
    Default: "ec2imagebuilder-eiger-infra"
  
Resources:
  AmazonEC2RoleForSSMPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: AmazonSSMManagedInstanceCore_And_ExtraConfigs
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
            - ssm:DescribeAssociation
            - ssm:GetDeployablePatchSnapshotForInstance
            - ssm:GetDocument
            - ssm:DescribeDocument
            - ssm:GetManifest
            - ssm:GetParameter
            - ssm:GetParameters
            - ssm:ListAssociations
            - ssm:ListInstanceAssociations
            - ssm:PutInventory
            - ssm:PutComplianceItems
            - ssm:PutConfigurePackageResult
            - ssm:UpdateAssociationStatus
            - ssm:UpdateInstanceAssociationStatus
            - ssm:UpdateInstanceInformation
            Resource:
            - "*"
          - Effect: Allow
            Action:
            - ssmmessages:CreateControlChannel
            - ssmmessages:CreateDataChannel
            - ssmmessages:OpenControlChannel
            - ssmmessages:OpenDataChannel
            Resource:
            - "*"
          - Effect: Allow
            Action:
            - ec2messages:AcknowledgeMessage
            - ec2messages:DeleteMessage
            - ec2messages:FailMessage
            - ec2messages:GetEndpoint
            - ec2messages:GetMessages
            - ec2messages:SendReply
            Resource:
            - "*"
          - Effect: Allow
            Action:
            - s3:Get*
            - s3:List*
            - s3-object-lambda:Get*
            - s3-object-lambda:List*
            Resource:
            - !Sub arn:aws:s3:::${S3DownloadBucket}
            - !Sub arn:aws:s3:::${S3DownloadBucket}/*
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:DescribeLogGroups
            - logs:DescribeLogStreams
            - logs:CreateLogGroup
            - logs:PutLogEvents
            Resource:
            - "*"
          - Effect: Allow
            Action:
            - ssm:PutParameter
            - ssm:DeleteParameter
            - ssm:PutParameters
            - ssm:DeleteParameters
            Resource:
            - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/Eiger-PostMigrationAutomation*
      Roles:
        - AmazonEC2RoleForSSM